= CAHIER DES CHARGES V1

Version 1 +

Date : 11 mai 2023 +

Equipe : BERNARD Julien, ESTRADE Prescilla, MALIQUE Manon +

Groupe 4A1

Projet : DailyBank - SAES 2.01 et 2.05

== Sommaire
* <<presentation_sujet>>
** <<contexte>>
** <<objectif>>
** <<identification_utilisateurs>>
* <<analyse_existant>> 
* <<analyse_besoins>> 
* <<livrables>> 
* <<analyse_contraintes>> 
** <<techniques>>
** <<organisationnelles>>

[[presentation_sujet]]
== 1. Presentation du sujet

[[contexte]]
=== 1.1 Contexte
Le contexte bancaire est marqué par la nécessité pour les banques de répondre aux exigences des clients en termes de rapidité et de digitalisation. 

La banque DailyBank souhaite développer une application JAVA-Oracle de gestion des comptes clients pour remplacer plusieurs outils obsolètes. Ce développement s’inscrit dans le cadre de la restructuration de ses services bancaires et l’application sera déployée dans les 100 agences que compte son réseau. 
[[objectif]]
=== 1.2 Objectif
Nous travaillerons à partir d’une application existante « Daily Bank » qu’il faudra adapter aux nouveaux besoins de la banque. La banque, à travers cette application veut moderniser ses outils et services bancaires. 
[[identification_utilisateurs]]
=== 1.3 Identification des utilisateurs
Il existe deux types d’utilisateurs : le guichetier et le chef d’agence. Le guichetier pourra créer un compte, le créditer, le débiter, effectuer un virement d’un compte à un autre et clôturer un compte. Quant au chef d’agence, il aura la possibilité de gérer les employés.

[[analyse_existant]]
== 2. Analyse de l’existant
=== Un guichetier peut :
* Modifier informations client (adresse, téléphone, …)
* Créer un nouveau client
* Consulter un compte
* Débiter un compte (BD) 

=== Un chef d’agence peut :
* Rendre inactif un client

[[analyse_besoins]]
== 3. Analyse des besoins
L’application doit permettre de gérer des comptes bancaires de dépôt pour des clients préalablement créés. Elle devra permettre de débiter, créditer un compte soit par virement c’est à dire un échange d’argent entre deux comptes distincts mais domiciliés dans le réseau bancaire, soit par une personne physique se présentant devant un guichet.

=== Description des fonctionnalités à réaliser :
* Ce que doit pouvoir faire un Guichetier :
** Créditer/débiter un compte (java et BD avec procédure stockée)
** Créer un compte
** Effectuer un virement de compte à compte
** Clôturer un compte
* Ce que doit pouvoir faire un Chef d’Agence :
** Gérer (faire le « CRUD ») les employés (guichetier et chef d’agence)

_CRUD: Create Read Update Delete_

[[livrables]]
== 4. Livrables
* Cahier des charges
* Gantt
* Documentation utilisateur
* Documentation technique
* Cahier de tests

[[analyse_contraintes]]
== 5. Analyse des contraintes

[[techniques]]
=== 5.1 Techniques
* Ressources : 
** Outils de développement : 
*** Java avec IHM (FX) IDE Eclipse
*** BD : Oracle Sql Developer
** Outil pour le Gantt : GanttProject
** Outil pour les documentations : ASCIIDOC
* Objectif : Application bancaire permettant de gérer des comptes bancaires de dépôt. Elle devra permettre de créer un compte, le débiter, le créditer un compte, d'effectuer un virement de compte à compte, de clôturer un compte et de gérer les employés (CRUD).
* Délais : +
** Vendredi 12 mai 12h : 
*** V1 du gantt en pdf
*** V1 du cahier des charges en asciidoc

[[organisationnelles]]
=== 5.2 Organisationnelles
* Outils de travail collaboratifs : 
** Github pour la gestion du projet (codes, documentations)
** Discord pour la communication
